//
//  OnboardingGenerator.swift
//  Classlly
//
//  Created by Robu Darius on 09.12.2025.
//


import SwiftUI
import SwiftData

class OnboardingGenerator {
    
    /// Generates dummy subjects and schedule data based on user input
    /// This is the "Magic Trick" - creating value from thin air
    @MainActor
    static func generateTemplate(context: ModelContext, subjectCount: Int, semesterEnd: Date) {
        // 1. Clean Slate (Optional: remove if you want to keep existing)
        // For onboarding, we assume fresh start or appending
        
        // 2. Define Template Data
        let subjectNames = ["Mathematics", "Physics", "Computer Science", "History", "Literature", "Chemistry", "Biology", "Economics", "Psychology", "Art"]
        let classrooms = ["Room 101", "Lab A", "Hall C", "Online", "Room 304"]
        
        // 3. Create Subjects
        for i in 0..<min(subjectCount, subjectNames.count) {
            let name = subjectNames[i]
            
            // Randomly assign days
            // Course: Mon/Wed or Tue/Thu
            let courseDays = (i % 2 == 0) ? [2, 4] : [3, 5] // Mon/Wed vs Tue/Thu
            let seminarDay = (i % 2 == 0) ? [6] : [2]       // Fri vs Mon
            
            let newSubject = Subject(
                title: name,
                courseTeacher: "Professor \(String(name.prefix(3)))", // Dummy teacher name
                courseClassroom: classrooms.randomElement() ?? "Room 101",
                courseStartTime: date(hour: 9 + i, minute: 0),
                courseEndTime: date(hour: 10 + i, minute: 30),
                courseDays: courseDays,
                courseFrequency: .weekly,
                seminarTeacher: "Asst. \(String(name.prefix(3)))",
                seminarClassroom: classrooms.randomElement() ?? "Lab B",
                seminarStartTime: date(hour: 14 + (i % 4), minute: 0),
                seminarEndTime: date(hour: 16 + (i % 4), minute: 0),
                seminarDays: seminarDay,
                seminarFrequency: .biweeklyOdd
            )
            
            context.insert(newSubject)
            
            // 4. Create a "Welcome" Task for the first subject
            if i == 0 {
                let welcomeTask = StudyTask(
                    title: "Review Syllabus for \(name)",
                    dueDate: Date().addingTimeInterval(86400 * 2), // 2 days from now
                    priority: .high,
                    subject: newSubject,
                    reminderTime: .hourBefore1,
                    isFlagged: true,
                    notes: "Generated by Classlly Setup"
                )
                context.insert(welcomeTask)
            }
        }
        
        // 5. Save Context
        do {
            try context.save()
            print(" Sticky Onboarding: Generated \(subjectCount) subjects.")
        } catch {
            print("Failed to save template data: \(error)")
        }
    }
    
    // Helper to generate time dates today
    private static func date(hour: Int, minute: Int) -> Date {
        return Calendar.current.date(bySettingHour: hour, minute: minute, second: 0, of: Date()) ?? Date()
    }
}